### PR TITLE
Update embassy dependencies

### PR DESCRIPTION
**Pull request by petekubiak**
This PR updates the embassy dependencies to the latest version, so that ector can be used with the latest version of embassy (without these changes there is a dependency clash with embassy v0.6.0).
We have also removed the `#[feature]` flags which have now been made stable, meaning that the repo as a whole no longer requires the nightly toolchain.

An integration test which had broken dependencies has been removed (see discussion below).

### CODE REVIEW

**Comment by lulf** [comment]
That's a good question, I've cloned your PR and tried to fix it, but I'm not sure what could be the problem here. This must be some kind of cargo resolving issue, because `cargo tree --format '{p} {f}'` shows that the features on `embassy-time` for enabling the builtin timer is set. 

TBH I don't think the integration tests add any value anymore now that the examples are much easier to run than they used to be.

**Comment by jamessizeland** [comment]
happy for me to remove the integration test?

**Comment by lulf** [comment]
I think it's ok to remove, they don't add much value and has been a source of annoyance for a long time.

**Comment by jamessizeland** [comment]
I might see if it can run in tokio instead first

**Comment by jamessizeland** [comment]
no idea! I'll remove and update the PR.

**Comment by petekubiak** [comment]
There's a clippy issue which needs resolving too, it's not in a file we've changed but clippy issues are set as errors. I noticed earlier there's another PR from February which was also aiming to update dependencies, and contains what I now realise is the fix for the clippy issue. Here is the relevant fix:
https://github.com/drogue-iot/ector/pull/18/commits/23f79bfef869bfad33aba821b9fc552027167619#diff-0e3fec3ae933f1e8228e1156fc37bb667d6c41ed64ed562558d009fccc9860f0

**Comment by jamessizeland** [comment]
Cool, I'll leave it for you to look at when you're back @petekubiak. We can consolidate the bits from the other PRs too I guess.

**Comment by petekubiak** [comment]
Ok I think this is ready for full review now.

**Review by lulf — APPROVED** [review]

**Pull request merged**
